### ISSUE TITLE
tlsConfig.BuildNameToCertificate is deprecated

### ISSUE THREAD

**Issue by TheMeier** [camptocamp/prometheus-puppetdb#42]
`go vet` fails with:

internal/puppetdb/puppetdb.go:76:3: tlsConfig.BuildNameToCertificate is deprecated: NameToCertificate only allows associating a single certificate with a given name. Leave that field nil to let the library select the first compatible chain from Certificates.  (SA1019)

**Comment by yann-soubeyrand** [comment]
Fixed in [v0.13.0](https://github.com/camptocamp/prometheus-puppetdb-sd/releases/tag/0.13.0).
